### ISSUE TITLE
[Breaking changes] Рефактор названий пропсов у компонентов для приведения к единому стандарту

### ISSUE THREAD

**Issue by ewgenius** [VKCOM/VKUI#1522]
Изменения в публичном апи, поэтому планируем на следующий мажорный релиз.
Если какие-то правки будут внесены с сохранением deprecated полей, в v5 их надо будет убрать

- [x] left/right vs before/after #1519 
- [x] ActionSheetItem#autoclose #1517 (#2383)
- [x] Alert#actions autoclose (#2383)
- [x] TabbarItem#label => indicator (#2381)
- [x] IconButton#icon => children (#2381)
- [x] ContentCard#image => src (#2381)
- [x] VKUITouchEventHander => VKUITouchEventHand**l**er (#2383)

- [x] Документация по миграции (#2351)

**Comment by land47** [comment]
PanelHeaderContentProps.aside -> PanelHeaderContentProps.after?

**Comment by thoughtspile** [comment]
Поблизости — почему везде вложенные кнопки делаются компонентами, а в Alert — массивом опций?
