### ISSUE TITLE
[Epic][Enhancement] Именованные экспорты

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2191]
Трекаем переход от дефолтных к именованным экспортам.

### Что делаем:
1. Добавляем правило линтера, ругающееся на дефолтные экспорты.
2. Исключаем все существующие дефолтные экспорты из этого правила.
3. Избавляемся от существующих дефолтных экспортов (постепенно, чтобы это легче было ревьюить и мерджить).

### Список компонентов и файлов:

 - [x] ActionSheetItem https://github.com/VKCOM/VKUI/pull/2219
 - [x] AdaptivityProvider https://github.com/VKCOM/VKUI/pull/2224
 - [x] Alert https://github.com/VKCOM/VKUI/pull/2225
 - [x] AppRoot https://github.com/VKCOM/VKUI/pull/2226
 - [x] Avatar https://github.com/VKCOM/VKUI/pull/2680
 - [x] Banner https://github.com/VKCOM/VKUI/issues/2509
 - [x] Button https://github.com/VKCOM/VKUI/pull/2400
 - [x] Card https://github.com/VKCOM/VKUI/pull/2242
 - [ ] CardGrid https://github.com/VKCOM/VKUI/pull/2713
 - [x] CardScroll https://github.com/VKCOM/VKUI/pull/2242
 - [x] Checkbox #2626
 - [x] Chip https://github.com/VKCOM/VKUI/pull/2244
 - [x] ChipsInput #2389
 - [x] ChipsSelect https://github.com/VKCOM/VKUI/pull/2289
 - [x] ConfigProvider
 - [x] ContentCard
 - [x] Counter #2658
 - [x] CustomScrollView
 - [x] CustomSelect #2389
 - [x] CustomSelectOption #2389
 - [x] DatePicker
 - [x] Div https://github.com/VKCOM/VKUI/pull/2290
 - [x] Epic
 - [x] File https://github.com/VKCOM/VKUI/pull/2527
 - [x] FixedLayout https://github.com/VKCOM/VKUI/pull/2678
 - [x] FormItem #2600
 - [x] FormLayout
 - [x] FormLayoutGroup #2600
 - [x] Gallery https://github.com/VKCOM/VKUI/pull/2686
 - [x] Gradient https://github.com/VKCOM/VKUI/pull/2243
 - [x] Group
 - [x] Header
 - [x] HorizontalScroll https://github.com/VKCOM/VKUI/pull/2400
 - [x] HorizontalScrollArrow https://github.com/VKCOM/VKUI/pull/2400
 - [x] IconButton
 - [x] InfoRow #2640
 - [x] Input #2389
 - [x] Link
 - [x] List
 - [x] ModalCard
 - [x] ModalDismissButton
 - [x] ModalPage
 - [x] #2617
 - [x] ModalRootContext
 - [x] NativeSelect https://github.com/VKCOM/VKUI/pull/2452
 - [x] #2616
 - [x] PanelHeaderBack
 - [x] PanelHeaderClose
 - [x] PanelHeaderContent
 - [x] PanelHeaderEdit
 - [x] PanelHeaderSubmit
 - [x] PanelSpinner #2614
 - [x] Placeholder #2610
 - [x] Progress #2596
 - [x] PromoBanner
 - [x] PullToRefresh https://github.com/VKCOM/VKUI/pull/2660
 - [x] PullToRefreshSpinner https://github.com/VKCOM/VKUI/pull/2660
 - [x] Radio #2609
 - [x] RangeSlider https://github.com/VKCOM/VKUI/pull/2683
 - [x] RichCell
 - [x] Root #2691
 - [x] ScreenSpinner #2624
 - [x] Search
 - [x] Select #2389
 - [x] SelectMimicry
 - [x] Separator
 - [x] SimpleCell
 - [x] SimpleCheckbox https://github.com/VKCOM/VKUI/pull/2289
 - [x] Slider https://github.com/VKCOM/VKUI/pull/2683
 - [x] SliderSwitch https://github.com/VKCOM/VKUI/commit/f05e82bbab508501519a1e27bea829c7c87dd918
 - [x] SliderSwitchButton
 - [x] Spinner #2615
 - [x] Tabbar
 - [x] TabbarItem
 - [x] Tabs
 - [x] TabsItem
 - [x] Tappable https://github.com/VKCOM/VKUI/pull/2714
 - [x] Textarea https://github.com/VKCOM/VKUI/pull/2677
 - [x] Tooltip
 - [x] TouchRootContext
 - [x] Typography/Caption
 - [x] Typography/Headline #2502
 - [x] Typography/Subhead https://github.com/VKCOM/VKUI/pull/2400
 - [x] #2611
 - [x] Typography/Title https://github.com/VKCOM/VKUI/pull/2400
 - [x] UsersStack #2661
 - [x] View #2692
 - [x] ViewInfinite https://github.com/VKCOM/VKUI/pull/2289
 - [x] lib/animate.ts
