### ISSUE TITLE
[EPIC]: Покрытие скриншотными тестами

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2856]
- [ ] [E2E] добавить тесты для ActionSheetItem
- [ ] [E2E] добавить тесты для ModalPage
- [ ] [E2E] добавить тесты для Badge
- [ ] [E2E] добавить тесты для Footer
- [ ] [E2E] добавить тесты для Spinner
- [ ] [E2E] добавить тесты для Separator
- [ ] [E2E] добавить тесты для SubnavigationBar
- [ ] [E2E] добавить тесты для File
- [ ] [E2E] добавить тесты для Select
- [ ] [E2E] добавить тесты для Div
- [ ] [E2E] добавить тесты для PanelSpinner
- [ ] [E2E] добавить тесты для ModalCardBase
- [ ] [E2E] добавить тесты для AdaptivityProvider (?)
- [ ] [E2E] добавить тесты для ColorSchemeProvider (?)
- [x] [E2E] добавить тесты для PanelHeaderButton (#7463)
- [x] [E2E] добавить тесты для PanelHeader
- [x] [E2E] добавить тесты для PanelHeaderContent (#7463)
- [x] [E2E] добавить тесты для PanelHeaderContext (#7463)
- [x] [E2E] добавить тесты для Epic (#7476)
- [x] [E2E] добавить тесты для TabbarItem (#7477)
- [x] [E2E] добавить тесты для FixedLayout (#7480)
- [x] [E2E] добавить тесты для Alert (https://github.com/VKCOM/VKUI/pull/4652)
- [x] [E2E] добавить тесты для ScreenSpinner (#7457)
- [x] [E2E] добавить тесты для Snackbar
- [x] [E2E] добавить тесты для ModalDismissButton
- [x] [E2E] добавить тесты для CardGrid (#7238)
- [x] [E2E] добавить тесты для Group
- [x] [E2E] добавить тесты для Gradient (https://github.com/VKCOM/VKUI/pull/5827)
- [x] [E2E] добавить тесты для HorizontalCell
- [x] [E2E] добавить тесты для Gallery (#7456)
- [x] [E2E] добавить тесты для Progress (https://github.com/VKCOM/VKUI/pull/5131)
- [x] [E2E] добавить тесты для TabsItem
- [x] [E2E] добавить тесты для PullToRefresh (https://github.com/VKCOM/VKUI/pull/5279)
- [x] [E2E] добавить тесты для Link
- [x] [E2E] добавить тесты для Spacing
- [x] [E2E] добавить тесты для WriteBar (https://github.com/VKCOM/VKUI/pull/4757)
- [x] [E2E] добавить тесты для FormLayout
- [x] [E2E] добавить тесты для FormField (#7489)
- [x] [E2E] добавить тесты для FormStatus (#7489)
- [x] [E2E] добавить тесты для DatePicker
- [x] [E2E] добавить тесты для SliderSwitch
- [x] [E2E] добавить тесты для PanelHeaderClose (#7463)
- [x] [E2E] добавить тесты для PanelHeaderBack (#7463)
- [x] [E2E] добавить тесты для PanelHeaderSubmit (#7463)
- [x] [E2E] добавить тесты для PanelHeaderEdit (#7463)
- [x] [E2E] добавить тесты для ChipsSelect (#7469)
- [x] [E2e] добавить тесты для CustomScrollView (#7481)
---

Это объемная задача -- перед тем как браться за отдельный компонент, конвертируйте задачу в отдельное issue
