### ISSUE TITLE
[Epic][v5][CSS Modules] Заменить динамические вычисления свойств на мапы

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#3415]
### Описание

> 📝 Все подробности читайте здесь [babel-plugin-transform-css-modules/README_ABOUT_UNSAFE.md](https://github.com/VKCOM/VKUI/blob/v5/packages/babel-plugin-transform-css-modules/README_ABOUT_UNSAFE.md)

## Вычисляемые названия свойства

Вот пример, как должно быть:

```diff
- styles[`Component--mode-${mode}`];
+ const modeClassNames = {
+   vertical: styles["Component--mode-vertical"],
+   horizontal: styles["Component--mode-horizontal"],
+ };
+ modeClassNames[mode];
```

## Утилитарные функции

Вызовы следующих функций:

- [x] [`getSizeXClassName()`](https://github.com/VKCOM/VKUI/blob/v5.2.0/packages/vkui/src/helpers/getSizeXClassName.ts) #4240
- [x] [`getSizeYClassName()`](https://github.com/VKCOM/VKUI/blob/v5.2.0/packages/vkui/src/helpers/getSizeYClassName.ts) #4257
- [x] [`getPlatformClassName()`](https://github.com/VKCOM/VKUI/blob/v5.2.0/packages/vkui/src/helpers/getPlatformClassName.ts) #4272
- [x] [`getViewWidthClassName()`](https://github.com/VKCOM/VKUI/blob/v5.2.0/packages/vkui/src/helpers/getViewWidthClassName.ts) #4273
- [x] [`getHoverClassName()`](https://github.com/VKCOM/VKUI/blob/v5.2.0/packages/vkui/src/helpers/getHoverClassName.ts) #4271
- [x] [`getPointerClassName()`](https://github.com/VKCOM/VKUI/blob/v5.2.0/packages/vkui/src/helpers/getPointerClassName.ts) #4271
- [x] [`getViewHeightClassName()`](https://github.com/VKCOM/VKUI/blob/v5.2.0/packages/vkui/src/helpers/getViewHeightClassName.ts) #4271

заменить вот таким образом:

```diff
- getSizeYClassName(styles["Component"], sizeY)
+ const sizeYClassNames = {
+   none: styles["Component--sizeY-none"],
+   compact: styles["Component--sizeY-compact"],
+   regular: styles["Component--sizeY-regular"],
+ };
+ sizeYClassNames[sizeY];
```

в случае, если какого-то из вариаций нет, использовать `null`:

```diff
- getSizeYClassName(styles["Component"], sizeY)
+ const sizeYClassNames = {
+   none: styles["Component--sizeY-none"],
+   compact: styles["Component--sizeY-compact"],
+   regular: null,
+ };
+ sizeYClassNames[sizeY];
```

---

## Чеклист

- [ ] [ActionSheetItem](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx)
- [ ] [Alert](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Alert/Alert.tsx)
- [x] [Avatar](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Avatar/Avatar.tsx)
- [ ] [Badge](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Badge/Badge.tsx)
- [ ] [Banner](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Banner/Banner.tsx)
- [ ] [BaseGallery](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/BaseGallery/BaseGallery.tsx)
- [ ] [Button](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Button/Button.tsx)
- [ ] [ButtonGroup](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/ButtonGroup/ButtonGroup.tsx)
- [ ] [Calendar](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Calendar/Calendar.tsx)
- [ ] [CalendarDay](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/CalendarDay/CalendarDay.tsx)
- [ ] [CalendarDays](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/CalendarDays/CalendarDays.tsx)
- [ ] [Card](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Card/Card.tsx)
- [ ] [CardGrid](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/CardGrid/CardGrid.tsx)
- [ ] [CardScroll](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/CardScroll/CardScroll.tsx)
- [ ] [CellButton](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/CellButton/CellButton.tsx)
- [ ] [FixedLayout](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/FixedLayout/FixedLayout.tsx)
- [ ] [FocusVisible](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/FocusVisible/FocusVisible.tsx)
- [ ] [FormField](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/FormField/FormField.tsx)
- [ ] [FormItem](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/FormItem/FormItem.tsx)
- [ ] [FormLayoutGroup](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.tsx)
- [ ] [Gradient](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Gradient/Gradient.tsx)
- [ ] [Group](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Group/Group.tsx)
- [ ] [Header](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Header/Header.tsx)
- [ ] [HorizontalCell](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/HorizontalCell/HorizontalCell.tsx)
- [ ] [HorizontalScroll](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx)
- [x] [ImageBase](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/ImageBase/ImageBase.tsx)
- [x] [ImageBase/ImageBaseBadge](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/ImageBase/ImageBaseBadge/ImageBaseBadge.tsx)
- [ ] [Input](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Input/Input.tsx)
- [ ] [MiniInfoCell](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/MiniInfoCell/MiniInfoCell.tsx)
- [ ] [ModalPage](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/ModalPage/ModalPage.tsx)
- [ ] [NativeSelect](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/NativeSelect/NativeSelect.tsx)
- [ ] [PopoutWrapper](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/PopoutWrapper/PopoutWrapper.tsx)
- [ ] [RadioGroup](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/RadioGroup/RadioGroup.tsx)
- [ ] [Removable](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Removable/Removable.tsx)
- [ ] [RichTooltip](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/RichTooltip/RichTooltip.tsx)
- [ ] [ScreenSpinner](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/ScreenSpinner/ScreenSpinner.tsx)
- [ ] [SegmentedControl](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/SegmentedControl/SegmentedControl.tsx)
- [ ] [Select](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Select/Select.tsx)
- [ ] [SelectMimicry](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx)
- [ ] [Snackbar](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Snackbar/Snackbar.tsx)
- [ ] [SubnavigationBar](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/SubnavigationBar/SubnavigationBar.tsx)
- [ ] [SubnavigationButton](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/SubnavigationButton/SubnavigationButton.tsx)
- [ ] [Tabs](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Tabs/Tabs.tsx)
- [ ] [TabsItem](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/TabsItem/TabsItem.tsx)
- [ ] [Tappable](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Tappable/Tappable.tsx)
- [ ] [TextTooltip](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/TextTooltip/TextTooltip.tsx)
- [ ] [Tooltip](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Tooltip/Tooltip.tsx)
- [ ] [Typography/Caption](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Typography/Caption/Caption.tsx)
- [ ] [Typography/Footnote](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Typography/Footnote/Footnote.tsx)
- [ ] [Typography/Headline](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Typography/Headline/Headline.tsx)
- [ ] [Typography/Paragraph](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Typography/Paragraph/Paragraph.tsx)
- [ ] [Typography/Subhead](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Typography/Subhead/Subhead.tsx)
- [ ] [Typography/Text](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Typography/Text/Text.tsx)
- [ ] [Typography/Title](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/Typography/Title/Title.tsx)
- [ ] [UsersStack](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/UsersStack/UsersStack.tsx)
- [ ] [WriteBarIcon](https://github.com/VKCOM/VKUI/tree/master/packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx)
