### ISSUE TITLE
[Epic]: Оптимизировать запуск e2e тестов в CI

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#4079]
### Описание

Для этого необходимо следующее:

- [x] Обновление деплоя на gh-pages, т.к. оно зачем-то грузит из lfs (#4046)
- [x] Кеширование git lfs (#4072)
- [x] Уменьшение размеров скриншотов, а то для айфона и пикселя они увеличены в 3 раза (#4067)
- [x] #4057

---

- related to #3712
