### ISSUE TITLE
[Tech]: Улучшить покрытие unit тестами

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#4768]
### Описание

Покрытие unit тестами на 21.04.2023

- **80.59%** Statements `5623/6977`
- **66.09%** Branches `3021/4571`
- **80.43%** Functions `1196/1487`
- **80.28%** Lines `5265/6558`

---

<details><summary>08.04.2023</summary>
<p>

- **78.49%** Statements `5377/6850` 
- **64.22%** Branches `2921/4548`
- **78.68%** Functions `1159/1473`
- **78.09%** Lines `5034/6446`

</p>
</details> 

```[tasklist]
### Компоненты с покрытием statements <80%
- [x] Улучшить покрытие Alert #7337
- [x] Улучшить покрытие Avatar #7315
- [x] Улучшить покрытие BaseGallery #7304
- [x] Улучшить покрытие CardScroll #7343
- [x] Улучшить покрытие ChipsInput #7310
- [x] Улучшить покрытие Calendar, CalendarHeader , CalendarRange, CalendarDay, CalendarTime  #7312
- [x] Улучшить покрытие CustomScrollView #7313
- [x] Улучшить покрытие CustomSelect #7307
- [x] Улучшить покрытие Cell #7323
- [x] Улучшить покрытие Checkbox #7352
- [x] Улучшить покрытие DateRangeInput #7309
- [x] Улучшить покрытие DateInput #7308
- [x] Улучшить покрытие DropZone #7311
- [x] Улучшить покрытие Flex, Group, SimpleGrid #7333
- [x] Улучшить покрытие FixedLayout #7322
- [x] Улучшить покрытие HorizontalScroll #7343
- [x] Улучшить покрытие Image, ImageBase, ImageBaseBadge, ImageBaseOverlay #7314
- [x] Улучшить покрытие List #7306
- [x] Улучшить покрытие ModalRoot #7344
- [x] Улучшить покрытие Pagination #7316
- [x] Улучшить покрытие Skeleton #7321
- [x] Улучшить покрытие Tabs #7332
- [ ] Улучшить покрытие AppearanceProvider (5/8)
- [ ] Улучшить покрытие AppRoot (145/202)
- [ ] Улучшить покрытие HoverPopper (7/32)
- [ ] Улучшить покрытие Popover (11/63)
- [ ] Улучшить покрытие PanelHeaderButton (22/35)
- [ ] Улучшить покрытие PopperArrow (15/21)
- [ ] Улучшить покрытие RichTooltip (4/6)
- [ ] Улучшить покрытие Snackbar (39/77)
- [ ] Улучшить покрытие Slider (11/15)
- [ ] Улучшить покрытие TextTooltip (5/7)
- [ ] Улучшить покрытие UsersStack (20/29)
- [ ] Улучшить покрытие WriteBarIcon (21/30)
```

**Comment by inomdzhon** [comment]
На 04.09.2025 год покрытие 96.02%

https://app.codecov.io/gh/VKCOM/VKUI

<img width="2216" height="1125" alt="Image" src="https://github.com/user-attachments/assets/7ed98c1d-b5af-4de4-8df7-cbcbb6f8d8a5" />

Текущую задачу закрою. Далее предлагаю создавать уже точечные по конкретным компонентам.
