### ISSUE TITLE
[Feature]: TODO [>=6]

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#5868]
### Описание

- [ ] vkui • src/components/ChipsSelect/ChipsSelect.tsx (#2518)

```
  355              hoverMode=""
  356:             // TODO [>=6]: add label customization
  357              aria-label={opened ? 'Скрыть' : 'Развернуть'}
```

- [ ] #4810

```
  83  
  84:   // TODO [>=6]: переместить хук в AppRoot (см. https://github.com/VKCOM/VKUI/issues/4810).
  85    useIsomorphicLayoutEffect(
```

- [x] #6158

https://github.com/VKCOM/VKUI/blob/6c6143d58f9ebf45edf7dd6ab2cf9a717bb9f10a/packages/vkui/src/components/RangeSlider/RangeSlider.tsx#L9-L11

- [ ] #6154

```
  105    if (process.env.NODE_ENV === 'development' && spaced !== undefined) {
  106:     // TODO [>=6]: Удалить spaced
  107      warn('Свойство spaced устарело и будет удалено в v6. Используйте autoSpaced');
```

- [x] #6155

https://github.com/VKCOM/VKUI/blob/b75794feb9250abb2baf35efd080233b10620594/packages/vkui/src/components/VisuallyHiddenInput/VisuallyHiddenInput.tsx#L13-L18

- [x] VKUI • styleguide/pages/integrations_vk_mini_apps.md:

```
    1: <!-- TODO [>=6] Удалить Предисловие -->
    2  

  210  
  211: <!--TODO [>=6] Удалить в коде ниже возврат выполнения функции и комментарий про VKUI v5 -->
  212  
```

- [x] vkui • src/components/ActionSheet/ActionSheet.tsx (#4694):

```
  109    if (process.env.NODE_ENV === 'development' && popupDirection) {
  110:     // TODO [>=6]: popupDirection
  111      warn('Свойство "popupDirection" будет удалено в v6. Используйте свойство "placement"');
```

- [x] vkui • src/components/ActionSheet/types.ts:

```
  17     */
  18:   toggleRef?: ToggleRef; // TODO [>=6]: сделать обязательным
  19    /**
```

- [x] vkui • src/components/AdaptivityProvider/AdaptivityProvider.tsx:

```
  24  }: AdaptivityProviderProps) => {
  25:   // TODO [>=6]: удалить использование хука (#5049)
  26    /* eslint-disable @typescript-eslint/naming-convention */

  36    if (process.env.NODE_ENV === 'development') {
  37:     // TODO [>=6]: удалить warn
  38      if (!LEGACY_disableInternalUseBridgeAdaptivity) {

  65  ) {
  66:   // TODO [>=6]: удалить блок кода c использованием LEGACY_bridge (#5049)
  67    //  https://github.com/VKCOM/VKUI/blob/v5.5.5/packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.tsx#L46-L92
```

- [x] vkui • src/components/AppRoot/AppRoot.tsx:

```
  104      if (!safeAreaInsets) {
  105:       // TODO [>=6]: удалить warn
  106        warn("[@vkontakte/vk-bridge] Интеграция VKUI с @vkontakte/vk-bridge устарела и будет удалена в v6. Используйте хук `useInsets()` из @vkontakte/vk-bridge-react и результат передайте в параметр `safeAreaInsets` (см. https://github.com/VKCOM/VKUI/issues/5049)"); // prettier-ignore
```

- [x] vkui • src/components/Banner/Banner.module.css:

```
  5  
  6: /* TODO [>=6]: удалить или прийти к padding*/
  7  .Banner--withPadding {
```

- [x] vkui • src/components/ConfigProvider/ConfigProvider.test.tsx:

```
   39    });
   40:   // TODO [>=6] Удалить этот тест на бэкпорт
   41    describe('[deprecated] test webviewType backport', () => {

  102        appearance: Appearance.DARK,
  103:       // TODO [>=6] Удалить webviewType
  104        webviewType: WebviewType.INTERNAL,

  112        ['platform', Platform.ANDROID],
  113:       // TODO [>=6] Удалить webviewType
  114        ['webviewType', WebviewType.VKAPPS],
```

- [x] vkui • src/components/ConfigProvider/ConfigProvider.tsx (vk-bridge)

<details><summary>Old info</summary>
<p>

```
  27     */
  28:   onDetectAppearanceByBridge?: () => void; // TODO [>=6]: удалить
  29    children: React.ReactNode;

  53  
  54:   // TODO [>=6]: Удалить данный бэкпорт
  55    const hasCustomPanelHeaderAfter =

  60    if (process.env.NODE_ENV === 'development') {
  61:     // TODO [>=6]: удалить warn
  62      let webviewTypeRule = '';

  78  
  79:   // TODO [>=6]: удалить использование хука
  80    const appearance = useAutoDetectAppearance(appearanceProp, onDetectAppearanceByBridge);
```

</p>
</details> 

```
  27     */
  28:   onDetectAppearanceByBridge?: () => void; // TODO [>=6]: удалить
  29    children: React.ReactNode;

  53  
  54:   // TODO [>=6]: Удалить данный бэкпорт
  55    const hasCustomPanelHeaderAfter =

  60    if (process.env.NODE_ENV === 'development') {
  61:     // TODO [>=6]: удалить warn
  62      let webviewTypeRule = '';

  78  
  79:   // TODO [>=6]: удалить onDetectAppearanceByBridge
  80    const appearance = useAutoDetectAppearance(appearanceProp, onDetectAppearanceByBridge);
```

- [x] vkui • src/components/ConfigProvider/ConfigProviderContext.tsx:

```
   6  /**
   7:  * TODO [>=6]: удалить enum (#5049).
   8   *

  30     */
  31:   isWebView: boolean; // TODO [>=6]: удалить коммент про v6 @vkontakte/vk-bridge выше
  32    /**

  83  export const ConfigProviderContext = React.createContext<ConfigProviderContextInterface>({
  84:   // TODO [>=6]: удалить свойство (#5049).
  85    webviewType: undefined,
  86:   // TODO [>=6]: сделать по умолчанию `false` (#5049).
  87    hasCustomPanelHeaderAfter: true,
  88    customPanelHeaderAfterMinWidth: 90,
  89:   // TODO [>=6]: удалить использование vkBridge. Использовать `false` вместо него (#5049).
  90    isWebView: vkBridge.isWebView(),
```

- [x] #6151

```
  545      (e) => {
  546:       // TODO [>=6]: удалить `onInputChangeProp`.
  547        if (onInputChangeProp) {
```

- [x] vkui • src/components/CustomSelectOption/CustomSelectOption.tsx:

```
  95    if (!!option && process.env.NODE_ENV === 'development') {
  96    if (!!option && process.env.NODE_ENV === 'development') {
  97:     // TODO [>=6]: Удалить св-во `option`
  97      warn('Свойство option было добавлено по ошибке и будет удалено в v6.0.0.');
  98      warn('Свойство option было добавлено по ошибке и будет удалено в v6.0.0.');
```

- [x] vkui • src/components/FixedLayout/FixedLayout.tsx:

```
  58    const platform = usePlatform();
  59:   const ref = useExternRef(getRootRef, getRef); // TODO [>=6]: удалить getRef
  60    const [width, setWidth] = React.useState<string | undefined>(undefined);
```

- [x] vkui • src/components/Footer/Footer.module.css

```
  2    display: block;
  3:   /* TODO [>=6]: переделать на padding */
  4    margin: 24px var(--vkui--size_base_padding_horizontal--regular);
```

- [x] vkui • src/components/ModalCardBase/ModalCardBase.module.css:

```
  77  /*
  78:  * TODO [>=6]: зачем этот стиль? Удалить?
  79  */
```

- [x] vkui • src/components/PanelHeader/LegacyPanelHeaderContent.tsx:

```
  15  /**
  16:  * TODO [>=6]: Удалить подкомпонент
  17   * @deprecated
```

- [x] vkui • src/components/PanelHeader/PanelHeader.tsx:

```
  79  
  80:   // TODO [>=6]: Удалить условие
  81    if (
```

- [x] vkui • src/components/Popper/Popper.tsx:

```
  230  
  231:   // TODO [>=6]: убрать getRef
  232    const handleRootRef = useExternRef<HTMLDivElement>(refs.setFloating, getRef, getRootRef);
```

- [x] vkui • src/components/PromoBanner/PromoBanner.tsx:

```
  49  
  50: // TODO [>=6]: Удалить компонент
  51  
```

- [x] vkui • src/components/PullToRefresh/PullToRefresh.tsx:

```
  167        const runTapticImpactOccurredCalled = onRefresh();
  168:       // TODO [>=6]: удалить блок кода (#5049)
  169        if (!runTapticImpactOccurredCalled) {
```

- [x] vkui • src/components/SimpleCell/SimpleCell.tsx:

```
  107    if (process.env.NODE_ENV === 'development' && expandable === true) {
  108    if (process.env.NODE_ENV === 'development' && expandable === true) {
  109:     // TODO [>=6]: Обновить типизацию для expandable свойства
  109      warn(
  110      warn(
```

- [x] vkui • src/components/Slider/Slider.tsx:

```
  55    /**
  56:    * TODO [>=6]: Расширить тип `event` с `React.ChangeEvent`.
  57     */

  65    /**
  66:    * TODO [>=6]: Расширить тип `event` с `React.ChangeEvent`.
  67     */

  74  export const Slider = ({
  75:   // TODO [>=6]: Выставить 1 как значение по умолчанию, чтобы было как в браузерном <input type="range" />
  76    step,
```

- [x] vkui • src/components/Spinner/Spinner.tsx:

```
  21      children = 'Загружается...',
  22:     // TODO [>=6]: Удалить автоматическое приведение aria-label
  23      'aria-label': ariaLabel = 'Загружается...',

  40  
  41:     // TODO [>=6]: Удалить варнинг
  42      if (process.env.NODE_ENV === 'development') {
```

- [x] vkui • src/components/UsersStack/UsersStack.tsx:

```
   33     * Вертикальный режим рекомендуется использовать с размером `m`
   34     * Вертикальный режим рекомендуется использовать с размером `m`
   35:    * TODO [>=6]: удалить

   35     * @deprecated
   36     * @deprecated

  186    if (process.env.NODE_ENV === 'development' && layout) {
  187    if (process.env.NODE_ENV === 'development' && layout) {
  188:     // TODO [>=6]: Удалить layout
  188      warn('Свойство "layout" будет удалено в v6. Используйте свойство "direction"');
  189      warn('Свойство "layout" будет удалено в v6. Используйте свойство "direction"');
```

- [x] vkui • src/helpers/appearance.ts:

```
  25  /**
  26:  * TODO [>=6]: удалить `helpers/appearance.ts` (#5049)
  27   * @deprecated v5.8.0
```

- [x] vkui • src/helpers/getPlatformClassName.ts:

```
  1: // TODO [>=6]: удалить этот хеллпер
  2  import { platform, PlatformType } from '../lib/platform';
```

- [x] vkui • src/hooks/useAutoDetectAppearance.tsx:

<details><summary>Old info</summary>
<p>

```
  63  /**
  64:  * TODO [>=6]: удалить хук (#5049)
  65   * @deprecated v5.8.0
```

</p>
</details> 

> [!IMPORTANT]
> Надо удалить привязку к vk-bridge, а не сам хук

- [x] vkui • src/hooks/useBridgeAdaptivity.ts:

```
  45  /**
  46:  * TODO [>=6]: удалить хук (#5049)
  47   * @deprecated v5.8.0
```

- [x] vkui • src/hooks/useInsets.ts:

```
  44  /**
  45:  * TODO [>=6]: удалить хук (#5049)
  46   * @deprecated v5.8.0
```

- [x] vkui • src/hoc/withInsets.ts:

```
/**
 * TODO [>=6]: удалить HOC (#5049)
 *
 * @deprecated v5.10.0
 */
```

- [x] vkui • src/lib/platform.ts:

```
  12  /**
  13:  * TODO [>=6]: удалить из VKUI
  14   *
```

- [x] vkui • src/lib/taptic.ts:

```
  3  /**
  4:  * TODO [>=6]: удалить хук (#5049)
  5   * @deprecated v5.8.0
```

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
