### ISSUE TITLE
[Epic]: Разрешить вопрос с нестабильными компонентами

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#6231]
### Описание

- [x] https://github.com/VKCOM/VKUI/issues/2518
- [x] https://github.com/VKCOM/VKUI/issues/2523
- [x] https://github.com/VKCOM/VKUI/issues/2769
- [x] https://github.com/VKCOM/VKUI/issues/6179
- [x] https://github.com/VKCOM/VKUI/issues/6208
- [x] https://github.com/VKCOM/VKUI/issues/6227

---

### `ViewInfinite`

Пока не будем трогать. Возможно его стоит вынести из VKUI.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
